# Docker Integration Test Profile
# Usage: Set SPRING_PROFILES_ACTIVE=docker in docker-compose-app.yml
# All required environment variables are injected from docker-compose-app.yml

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop  # Clean DB for each test run
    show-sql: false  # Reduce log volume

# Logging
logging:
  level:
    com.unisync: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO